source:
  file: data/employees.csv

transformations:

  - type: filter
    condition: salary > 50000

  - type: select
    columns:
      - id
      - name
      - salary

  - type: derive
    column: salary_band
    expression: "CASE WHEN salary > 70000 THEN 'HIGH' ELSE 'LOW' END"

target:
  type: postgres
  host: localhost
  port: 5432
  database: postgres
  table: employee_filtered
  user: postgres
  password: "1234"