source:
  file: data/employees.csv

transformations:

  - type: filter
    condition: salary > 50000

  - type: select
    columns:
      - id
      - name

target:
  type: postgres
  host: localhost
  port: 5432
  database: postgres
  table: employee_filtered
  user: postgres
  password: "1234"